import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'  // Add this import
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Include necessary head elements here */}
      </head>
      <body className="bg-slate">
        <Image
          alt="construct"
          src="https://app.constructn.ai/_next/static/media/logo-yellow.1fc0a594.svg"
          width={268}
          height={8}
          decoding="async"
          loading="lazy"
          className="absolute top-0 left-0 p-4 pl-6"
        />
        {children}
      </body>
    </html>
  )
}
