import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'  // Add this import
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Include necessary head elements here */}
      </head>
      <body className="bg-slate">
        {children}
      </body>
    </html>
  )
}
